name: CI Pipeline for Prod

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Extract tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./kkambbak/gradlew

      - name: Build with Gradle
        run: |
          cd kkambbak
          ./gradlew bootJar -x test

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: kkambbak/build/libs/*.jar

  dockerize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Extract tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: kkambbak/build/libs

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kkambbak:${{ steps.tag.outputs.TAG_NAME }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/kkambbak:${{ steps.tag.outputs.TAG_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/kkambbak:latest

      - name: Notify Discord (배포 성공)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{
              "embeds": [
                {
                  "color": 65280,
                  "title": "✅ 운영 서버 배포 성공!",
                  "fields": [
                    {
                      "name": "Repository",
                      "value": "'"${GITHUB_REPOSITORY}"'",
                      "inline": true
                    },
                    {
                      "name": "Tag",
                      "value": "'"${{ steps.tag.outputs.TAG_NAME }}"'",
                      "inline": true
                    },
                    {
                      "name": "Commit",
                      "value": "'"${GITHUB_SHA:0:7}"'",
                      "inline": true
                    }
                  ]
                }
              ]
            }' ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord (배포 실패)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d '{
              "embeds": [
                {
                  "color": 16711680,
                  "title": "❌ 운영 서버 배포 실패!",
                  "fields": [
                    {
                      "name": "Repository",
                      "value": "'"${GITHUB_REPOSITORY}"'",
                      "inline": true
                    },
                    {
                      "name": "Tag",
                      "value": "'"${{ steps.tag.outputs.TAG_NAME }}"'",
                      "inline": true
                    },
                    {
                      "name": "Commit",
                      "value": "'"${GITHUB_SHA:0:7}"'",
                      "inline": true
                    }
                  ]
                }
              ]
            }' ${{ secrets.DISCORD_WEBHOOK }}